### PR TITLE
Fix #92: Special case connecting to wildcard on macOS

### LINKED ISSUE #92: Binding to wildcard "0.0.0.0" then connecting throws `ConnectException` on macOS
Reproducer in https://github.com/armanbilge/epollcat/commit/6c3ea7e77bf9ddb901983d434655546ce1ac414a.

https://github.com/armanbilge/epollcat/blob/6c3ea7e77bf9ddb901983d434655546ce1ac414a/tests/shared/src/test/scala/epollcat/TcpSuite.scala#L244-L254

### PR DESCRIPTION
**Pull request by LeeTibbert**
Fix #92 

Arman supplied the test case; I am supplying a proposed fix & the bugs.

The details behind the fix is pretty complicated, so I will add it to Issue #92.  

TL; DR;    Cause macOS to do what Linux does, convert ::0 to ::1 when connecting.

I welcome improvements to the naming, format, and, especially, the actual Scala.

### CODE REVIEW

**Comment by armanbilge** [comment]
Lee, thank you very much for the fix, much appreciated :)

> The details behind the fix is pretty complicated, so I will add it to Issue #92.

Before I take a closer look, were you planning to add more to that issue? No rush, I just didn't want to leave your PR hanging without review. Thanks!

**Comment by LeeTibbert** [comment]
> Before I take a closer look, were you planning to add more to that issue? No rush, I just didn't want to leave your
>  PR hanging without review. Thanks!

Understood. Sorry for the delay at my end. 

The fix itself should not change.  I hate "special case" code on principal and experience; it
always comes back to bite me.....     Here it is, I think, the least bad alternative.

In the issue, I will fill in a trace of my reasoning. Probably Wednesday at this point,
unless I am holding you up.

File: tests/shared/src/test/scala/epollcat/TcpSuite.scala [hunk 1]
```diff
@@ -209,6 +209,33 @@ class TcpSuite extends EpollcatSuite {
...
+      .open
+      .evalTap(_.setOption(StandardSocketOptions.SO_REUSEADDR, java.lang.Boolean.TRUE))
+      .evalTap(_.bind(new InetSocketAddress("0.0.0.0", 0)))
+      // If IPv6 active, IPv4 "0.0.0.0" will have been converted to IPv6 "::0"
+      // because the socket fd was pre-allocated as IPv6.
+      .use { server =>
+        IOSocketChannel.open.use { clientCh =>
+          if (true) { // IPv6 connect
+            server.localAddress.flatMap(clientCh.connect(_))
+          } else { // IPv4 connect
```
Comment (armanbilge) [inline tests/shared/src/test/scala/epollcat/TcpSuite.scala:227]: Why the two cases with the hard-coded `true`?

**Review by armanbilge — APPROVED** [review]
As far as special cases go, this one looks pretty clean. After reading the analysis in https://github.com/armanbilge/epollcat/issues/92#issuecomment-1330769693 I also think this is the least-bad strategy available.

File: tests/shared/src/test/scala/epollcat/TcpSuite.scala (hunk 1 above)
Comment (LeeTibbert) [reply tests/shared/src/test/scala/epollcat/TcpSuite.scala:227]: To document and allow toggling IPv6/IPv4. 

I can convert the IPv4 case to a /* */ block.  When I had it that way, it took
some verbiage and was even more confusing.   Please advise.  No problems

Thank you for review.  People are going to try tracing this stuff.
changing to comment.

Comment (LeeTibbert) [reply tests/shared/src/test/scala/epollcat/TcpSuite.scala]: I converted the IPv4 option to a block comment. I hope that makes it less confusing.

Whilst chasing this issue, I found it more than handy to have that code readily
available and not to have to re-create it.

Comment (armanbilge) [reply tests/shared/src/test/scala/epollcat/TcpSuite.scala]: Makes sense. Thanks for clarifying!
